name: Build Chrome Extension on main push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run npm build
        run: npm run build

      - name: Create Zip of Browser Extension
        run: |
           zip -r generate-gpt-mail-extension.zip generate-gpt-mail-extension

      - name: Upload Zip Archive
        uses: actions/upload-artifact@v2
        with:
          name: generate-gpt-mail-extension
          path: generate-gpt-mail-extension.zip